#+BIBLIOGRAPHY:  ../../../library
#+TITLE: Modeling a Commercial Choice-based Cinematic Interactive Narrative using Story Intention Graphs
* Abstract
Many contemporary interactive digital narratives consist of cinematic
content that combines performance, sound and dialogue with
conventional patterns of player interactions that dictate the story
path. The non-linear nature of the content makes applying methods of
annotation and analysis currently used in text and film challenging,
as any particular experience may differ in significant ways and a
player's response may occur at different times in the experience while
still applying to a particular event. As a result, most studies
approach analyzing player experience using either qualitative methods
or quantitative methods alone, and often these studies focus on
experimental systems. We developed a coding scheme that captures
opportunities and decisions and provides hooks for annotating story
content and player affective response. We plan to annotate recorded
player traversals of /The Wolf Among Us/, a choice-based adventure
game, incorporating a non-verbal report method, the /Sensual
Evaluation Instrument/ \cite{Isbister2006-sc}, guided by a text-based
intermediate format that models the game logic. We use David Elson's
/Story Intention Graph/ to annotate the story content
\cite{Elson2012-pi}. The proposed study will be evaluated by whether
the responses capture salient story content between different
traversals effectively. We describe a proposed baseline method of
manually identifying shared story segments and tagging emotional
content of scenes.
* Body
** Introduction
Interactive storytelling uses the capabilities of computational media
to dynamically assemble stories based on player input and/or on an
underlying simulation of a world. These narratives are expressed in a
variety of immersion levels: text-based for interactive fiction and
first-person drawing for the interactive drama /Facade/
\cite{Mateas2003-ty}. A subgenre of adventure games uses simple
choices and cinematic aesthetics and is amenable to approaches from
traditional narratives. The research program described in this paper
examines a simpler form of interactive narrative using a computational
model of narrative to analyze player emotional responses. /The Wolf
Among Us/ by Telltale Games was chosen for its consistent story
structure along with a nuanced narrative and critical acclaim, as well
as a thriving fanbase. We believe that the work's complex network of
character goals and their relationships with the player would provide
a good test for assessing the efficacy of understanding ways that a
specific work's combination of opportunities and decisions combined to
create a player's emotional experience. This paper describes our
initial work on developing an annotation schema and a proposed
methodology for developing a corpus-based approach to analyzing a
subgenre of interactive digital narratives (IDN).

*** Motivation
Interactive narratives are challenging to study with the analytic
methods usually applied to linear narratives. Their variations prevent
simple annotation techniques based on time or position from being
compared, and the player response is often determined by choices and
the order or selection of content. The proposed methodology of
annotating story traversals builds on efforts within the computational
narratology community focused on corpora and formal models. These
approaches owe a debt to the original corpus study of Russian folk
tales by Vladimir Propp \cite{Propp1928-pk}. More recently, Finlayson
has led the charge in standardizing annotation approaches in narrative
modeling. Finlayson conducted a study of the use of corpora that
concluded that text, is prioritized given the availability of tools
\cite{Finlayson2013-wi}, although the only game logs that he cited
were those of Orkin in the game EAT & RUN \cite{Orkin2010-vr}. The
program outlined in this paper takes a similar approach, proposing to
record and

Many studies conducted on IDNs have opted for a different approach,
focusing on short, experimental works such as Facade
\cite{Seif_El-Nasr2013-hp}, whose story differs drastically each
playthrough and is not suited to corpus based
approaches. Computational analysis of contemporary interactive
narratives is still in its infancy, as no agreed methods or corpora
are available. Current approaches to understanding player experience
in IDN include focusing on quantitative aspects \cite{Marczak2013-np},
developing objective measures\cite{Szilas2014-fd}, using phenomenology
\cite{Seif_El-Nasr2013-hp}, reading and interpreting the processes
themselves (\cite{Wardrip-fruin2006-je}, hermeneutics
\cite{Arjoranta2015-rw} and identifying design patterns
\cite{Reed2014-qw}. None of these approaches incorporate the
underlying narrative content and its influence on other aspects of the
player experience and none relate experiences to a consistent model of
narrative. A consistent model would shared content between traversals
to be identified enable subjective interpretation to be incorporated
separately from objective measures. Such a representation, like those
enabling annotated datasets in linguistics, could be used to identify
patterns and new relationships that are not obvious otherwise.

Tanenbaum argues that we should focus on interactive narratives to
understand their readerly pleasure through their bounded agency
\cite{Tanenbaum2011-yu} rather than the more popular notion of agency
that involves a player taking actions and seeing the results. This
position also suggests that techniques currently being used to study
linear narrative could be adapted to study non-linear narrative. That
goal, of extending and adapting a model of linear narrative to
non-linear narrative, supports the objective of better understanding
the nature of player's experience while interacting with story content
in an interactive narrative.

What is the nature of the content that is salient to the player's
experience in these works? Noah Wardrip-Fruin describes computational
media in terms of three components: data, process, and surface
\cite{Wardrip-Fruin2009-pe}. The primary characteristic of content in
this genre is that the density of meaning shown on the surface but
otherwise interpreted by players. Works such as those created by
Telltale Games rely heavily on hand-authored narrative dialogue and
human performances (data) rather than generated or simulated content
found in Emily Short and Richard Evan's Versu \cite{Evans2014-nk} or
the model of social games at the core of Joshua McCoy et al's Prom
Week (process). Additionally, the procedural complexity is limited to
simple state tracking and varying the content shown after a particular
decision point.

The model of story that describes the underlying story content is
critical to associating player experience with the work itself. David
Elson created the Story Intention Graph to be a descriptive model,
representing the mental simulation that naturally takes place in the
minds of readers of how agents interact: their values, the goals they
pursue and the network of causally linked events that make up actions
taken in those pursuits. For the purposes of the present work, Elson's
data structure provides a structure for information about events,
agents and affective goals using a graph representation. This
information is hypothesized to be sufficient to predict, given
previous samples of player choices, future moments of potential player
emotion. *Emotions* are a challenging phenomena to quantify, but for
the purpose of this paper they are defined as moments of internal
sensations associated with receiving information and are often mapped
on two axes: valence (positive/negative) and arousal (high/low). They
may or may not be associated with facial expressions or other
physiological indicators such as heartrate or skin conductivity,
though these may be useful in detecting potential states.

The remainder of this paper is organized as follows: We first define
the specific subgenre of IDN, cinematic choice-based
adventure games, and its suitability for this study and how we
captured the salient information in a schema. Next, we describe a
sequence of proposed studies and efforts that address the goal of
annotating existing interactive narrative playthroughs with emotional
and story content, identify possible patterns or relationships for how
the story structure and recorded emotions relate and use it to predict
player emotional experiences in a new episode of the series. We
describe the initial results of the first effort of transcribing and
annotating a non-textual traversal of an interactive narrative for
encoding with emotional events. Finally, we discuss direction for
future work and conclusions.

*** Cinematic choice-based adventure (CCBA) games
Telltale Game's The Wolf Among Us (TWAU) was released in 2013 for
multiple platforms \cite{Telltale_Games2013-hz}. The game received
numerous positive critical reviews and is a mature work in the
subgenre. Its story is conveyed through spoken dialogue, animated
performance and cinematography. The game's story has even been
translated into a comic book, the original media of the Fables series
on which the game is based \cite{Sturges2014-ua}. This section locates
the work in a subgenre of adventure game and identifies and justifies
an annotation schema created for it.

The subgenre of CCAG has several primary features: the story content
can be represented as a graph whose elements often have key order
relationships and is for entirely bespoke. The label "cinematic
choice-based adventure game" was chosen not because it is the popular
name. CCAG could be considered a hybrid of the point-and-click
adventure game and a descendent of what was called interactive
cinema. CCAG was chosen for how the label highlights the primary
mechanics (making choices) and the primary representational mode
(cinematic) as well as including the historical genre of adventure
games which is characterized by distinct authored player-character(s)
and an emphasis on story over combat.

The adventure game genre is often put in opposition to genres which
promote more player freedom, such as in Massively Multiplayer Role
Playing Games (MMORPGs) or Open World RPGs which allow players to
create and develop their own character. Clara Fernandez-Vara describes
in her dissertation how adventure games shape "the means by which the
player restores the behavior that is expected by playing the game"
\cite{Fernandez_Vara2009-mt}. In other words, in adventure games, the
player takes actions that are authored by the game's creator rather
than have those actions emerge from the system's behaviors. The
player's choices vary the way in which that performance is carried out
as well as whether certain key facts are true or omitted which color
and vary the reception of a plot. Most decisions and actions only have
an impact on the pacing or variation of the performance rather than
changes in the plot, such as the timing for choosing menu options or
choosing two options that have the same content play afterward but
which have apparent different descriptive text.

TWAU is episodic: future episodes must account for selected previous
player decisions, although these are usually limited to decisions that
have an ontological effect on the world (including the memories of the
characters). Other non-episodic games, such as Heavy Rain[fn:4], are
closely related in their operational logics and are suitable
candidates for using the annotation methods detailed here.

Games in this subgenre conserve content and maximizing narrative
payoffs among all possible traversals, this subgenre is ideally suited
to annotation using SIG, as the player's goals and intentions are
rewarded for small perturbations while the story remains relatively
consistent.

** Story Intention Graphs
The Story Intention Graph (SIG) schemata were developed by David Elson
as a set of discourse relations to represent key relationships among
concepts such as goals, values and agents present in textual
narratives using concepts from narrative theory. It consists of three
layers: a *textual layer*, which contains relevant (but not
exhaustive) spans of text from the source textual story. These are
connected to a set of propositions and states mapped to spans of text
in the text layer. in a layer that captures the described happenings
as a *timeline layer*. Finally, there is an *interpretive layer*,
where propositions are linked to agent goals, plans, and values.

Elson found that the SIG schemata, even without representing
individual propositions, was more successful than alternative methods
at identifying similarities in the stories. It is this structural
resiliency amongst annotators that we are interested in, as well as
the particular enforcement of the schema for each action to be related
both to a character and to an end value. By encoding the values
pursued by characters, we hypothesize that certain relationships will
emerge that will predict potential points where players may respond
emotionally. 

** Methodology and Study Design
The proposed study requires the development of new methodology. To the
authors' knowledge, there has been no usage of a formal model of
narrative to annotate a pre-existing non-textual interactive digital
narrative. This section describes the sequence of completed and
proposed steps that enables the work to be annotated and analyzed. The
first stage is to select and adapt a narrative model and coding schema
that can represent relationships between events and decisions and the
gameplay itself. The second step is to use that model to annotate a
set of "natural" traversals of users who are also reporting emotional
events. The third step is to analyze the emotional content with
respect to the story structure and player decisions, taking into
account self-reported information such as motivation and documenting
decisions. The fourth step develops an algorithm to associate content
with player emotion and locate possible situations giving rise to it.
This is followed by another study that validates the algorithm on
different content to assess the success of the tool.

*** Using a Model to Annotate Narrative Structure
For linear media, traditional annotation approaches use text spans or
video timecodes to associate metadata. This won't necessarily be
useful when content can appear or not appear based on player input,
and where timing can vary significantly.

First, the narrative structure needs to be available for
annotation. This means that content should be identifiable
consistently across different traversals. Further, this model should
be capable of identifying complex relationships between decisions and
outcomes as understood by agents within the story. Given these
requirements, the SIG schemata was selected due to its ability to map
elements directly onto text spans and its ability to separate the
information layers of events inferred and events represented. In order
to annotate a game with SIG, the following requirements for an
intermediate format emerged:

  1. It must be in a text format, at least initially, given
     availability of SIG annotation software
  2. Be capable of adding additional traversal content without
     redoing, deleting or altering previous traversal content. This
     would allow comparison of content amongst traversals, or indicate
     content that was revisited in a loop.

We began with the scope of the first episode, focusing on what we are
calling a "natural traversal," which is a a first encounter of a
player to the game and story where the events and outcomes are not
known. In order to assess the annotation method before collecting data
from study participants, we decided to test the transcription and
narrative annotation using an existing streamed video posted online of
a game traversal. A video by creator-performer Felix Arvid Ulf
Kjellberg, better known as "PewDiePie", was selected
\cite{Kjellberg2013-fn}e based on its completeness as well as the
presence of additional think-aloud by the performer. The actual
results of using a streamer are interesting and left to a future
study, while the present study focuses on individual players
encountering a work outside of a streaming context. To understand the
nature of the content, we reconstructed the gameplay content from the
video using a rational reconstruction approach of the underlying
model. This enabled us to document where player input was provided and
to think about how to represent it in a coding schema. 

There are a number of tools now available to author narratives based
on a model of lexia and links, including Ink, Twine, Ren'Py and
ChoiceScript. These tools enable authors to create textual or visual
narratives with various mechanisms to direct the player along
particular paths, or traversals. One of the disadvantages of the
popular authoring tools is a lack of a formal model of the underlying
structures -- with the idioms and convenience of syntax and relieving
authoring burdens the primary goal. Of the possible options, Inkl was
released an open source version of their narrative scripting language,
Ink. Ink is capable of representing all of the story-related
structures present in the game, including representing variables, as
well as being a pure text format.

Ink provided the following advantages as an intermediate format: It
can represent state variables, it has a simple means of annotating
lines with metadata such as character, it can concisely show
converging traversal threads and player choices and it is in an
easy-to-read text format source code. This first pilot involved
recording both ink and scheharazade annotations [fn:2].

*** User Study
We are planning to conduct a user study by having between 6 and 8
players play through episode one of TWAU . We will record the player's
report of their emotional experience using the Sensual Evaluation
Instrument (SEI) \cite{Laaksolahti2009-uw} as well as more traditional
surveys and a structured interview. These sessions will be recorded
with gameplay footage to allow for transcribing the traversals using
the method described above.

We hypothesize that the study will show consistent reactions during
moments where the tension is high, when the information revealed is
surprising and when the player's character is emotionally
involved. This translates to propositions in the model when a
character goal is either actualized or not. The emotions themselves
will vary based on a player's values as expressed through their
decisions. For instance, the player may decide to give Faith money in
one of the earlier scenes, indicating that the player is performing a
softer, more generous Bigby, and is thus more likely to feel bad for
ripping off the arm of another character later (or not ripping it off
at all). The value at stake in both cases is justice, though a justice
that is more broadly interpreted.

*** Iterations on SIG
The intermediate format of INK was adopted for two reasons. First,
transcribed player traversals did not capture the underlying
structure, and instead presented a simple linearization. This shifted
the burden of associating identical content in different traversals to
that of the annotator, and is not supported in the current annotation
tool (Scheherazade) or the text layer in the SIG schemata. Based on an
initial encoding of the YouTube playthrough video using the baseline
method, we hypothesize that certain patterns and connections between
previous decisions will be significant in identifying a player's
response. These connections will be rely on capturing the player's
responses to the decision logic of the genre and may require additions
to the SIG schema. If SIG schema can be extended to incorporate choice
structures and state tracking, then the intermediate format may no
longer be needed. The additions will require a means of uniquely
locating a state within a traversal, using an approach similar to that
of Playspecs \cite{Osborn2015-gr}.

In addition to extending the text layer of SIG to incorporate choice
paths and non-textual content, we anticipate the need for a tool to
facilitate the annotation process that associates the video footage of
gameplay traversals with story elements from the SIG in addition to
the player's emotional expressions.

A second user study, this time focusing on the second episode of TWAU,
will be run using the same procedure as the first, namely having
subjects play through the game while using the SEI. The extensions to
SIG and the original method will be applied to these traversals, and
the resulting predictions will be evaluated for whether they identify
potential points where players may experience emotion.

** Toward Computational Analysis of Interactive Digital Narratives
The primary goal of analyzing narratives with a rich dataset enabled
by a computational models of narrative is to discover insights that
might lie hidden beneath the surface experience or which may be
invisible without the full set of decisions represented by multiple
players.  This potential to understand the multifaceted role of
interactive narratives motivates the work ahead in creating the
datasets that will enable us to refine both the methods of evaluating
and representing models of narrative as well as leveraging them to
understand the player experience.

We presented a description of the initial coding schema developed to
annotate a corpus of interactive digital narrative playthroughs, and
provided a "pre-registration" of a program of proposed efforts that
measure emotional experiences from players of a released CCBA and plan
to extend an existing computational model of narrative to predicting
them. We believe that the availability of open datasets that can be
annotated and studied will provide researchers in the field with a
valuable resource for conducting further studies on the player
behavior as well as test future models of narrative, ultimately
facilitating future authoring tools designed to support creation of
interactive digital narratives to support eliciting particular
emotions through a combination of story architecture, interactive
decision selection and game design.

* Footnotes

[fn:2] the reconstructed ink file from the video playthrough is here:
[http://lucidbard.com/ink/TWAU_001.ink], the first episode's SIG
encoding: [http://lucidbard.com/ink/TWAU_001.vgl]. /Scheherazade/ can
be downloaded at [http://www.cs.columbia.edu/~delson/software.shtml].


[fn:3] That is, stories which consist of characters and not the broader sense sometimes used which could incorporate movies or comics
[fn:4] Quantic Dream, 2010
[fn:8] labeled deterministic, even though these works could branch and
Chris Crawford sense of instantial \cite{Crawford1982} could just as
well apply
[fn:9] This is influenced by Michael Mateas' concept of "content
selection architectures" as a useful way to describe how various types
of content and the configuration of the systems that organize them can
be compared. \cite{Mateas2015}
[fn:6] Quantic Dream, 2010
[fn:1] One recent Telltale Games work, Minecraft, uses a sandbox-style
creation game based on voxels as its basis, which departs from
previous works that use either comics or television.
